server {
    listen 80;
    server_name 22ccha.duckdns.org;

    # Let's Encrypt 자동 갱신 및 검증용 경로
    location /.well-known/acme-challenge/ {
        root /var/www/certbot;
    }

    # HTTP 접속 시 HTTPS로 301 자동 리다이렉트
    location / {
        return 301 https://$host$request_uri;
    }
}

server {
    listen 443 ssl;
    server_name 22ccha.duckdns.org;

    # 발급받은 Let's Encrypt SSL 인증서 경로
    ssl_certificate /etc/letsencrypt/live/22ccha.duckdns.org/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/22ccha.duckdns.org/privkey.pem;

    location / {
        proxy_pass http://web:8000;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}